#!/bin/sh
# vim: set ft=sh sw=2 et :

install_packages() {
  sudo dnf install tmux fzf, @development-tools make jq ripgrep zsh fuse-libs

  curl -sS https://starship.rs/install.sh | sh
  # TODO: Install JetBrains Mono Nerd Font
  # TODO: Marble Gnome Shell Theme, WE10OS cursor theme, Tela Black icons pack
  # GNOME Extensions:
  # GNOME Tweaks 
  sudo dnf install gnome-tweaks

  # OhMyZsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  # Flatpak: Google Chrome, KeePassXC
  flatpak install flathub com.google.Chrome
  flatpak install flathub org.keepassxc.KeePassXC
}

install_langs() {
  # Node, pnpm
  curl -fsSL https://fnm.vercel.app/install | bash
  fnm install --lts
  corepack enable pnpm && pnpm -v

  # Install go
  wget https://go.dev/dl/go1.25.3.linux-amd64.tar.gz
  sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.25.3.linux-amd64.tar.gz

  # Install Rust, eza
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  # TODO: Rust Nightly
  cargo install eza
}

install_packages()
install_langs()
